services:
  - type: web
    name: chanakya-backend
    env: node
    nodeVersion: 18
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: MONGO_URI
        fromEnv: MONGO_URI
      - key: JWT_SECRET
        fromEnv: JWT_SECRET
      - key: FRONTEND_URL
        fromEnv: FRONTEND_URL
